ASM_Duy/src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContactRepository::class)]
class Contact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

   
    

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $phone_number = null;

    #[ORM\Column(length: 255)]
    private ?string $title_name = null;

    #[ORM\Column(length: 255)]
    private ?string $note = null;

    public function getId(): ?int
    {
        return $this->id;
    }

   

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getTitleName(): ?string
    {
        return $this->title_name;
    }

    public function setTitleName(string $title_name): static
    {
        $this->title_name = $title_name;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(string $note): static
    {
        $this->note = $note;

        return $this;
    }
}

ASM_Duy/src/Form/ContactType.php
<?php

namespace App\Form;

use App\Entity\Contact;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('first_name')
            ->add('last_name')
            ->add('email')
            ->add('phone_number')
            ->add('title_name')
            ->add('note')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Contact::class,
        ]);
    }
}

ASM_Duy/src/Controller/ContactController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Form\ContactType;
use App\Repository\ContactRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/contact')]
class ContactController extends AbstractController
{
    #[Route('/', name: 'app_contact_index', methods: ['GET'])]
    public function index(ContactRepository $contactRepository): Response
    {
        return $this->render('contact/index.html.twig', [
            'contacts' => $contactRepository->findAll(),
        ]);
    }

    #[Route('new', name: 'app_contact_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ContactRepository $contactRepository): Response
    {
        $contact = new Contact();
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactRepository->save($contact, true);

            return $this->redirectToRoute('app_home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contact/new.html.twig', [
            'contact' => $contact,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_contact_show', methods: ['GET'])]
    public function show(Contact $contact): Response
    {
        return $this->render('contact/show.html.twig', [
            'contact' => $contact,
        ]);
    }

   
    #[Route('/{id}', name: 'app_contact_delete', methods: ['POST'])]
    public function delete(Request $request, Contact $contact, ContactRepository $contactRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contact->getId(), $request->request->get('_token'))) {
            $contactRepository->remove($contact, true);
        }

        return $this->redirectToRoute('app_contact_index', [], Response::HTTP_SEE_OTHER);
    }
   }

ASM_Duy/templates/contact/_delete_form.html.twig
<form method="post" action="{{ path('app_contact_delete', {'id': contact.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contact.id) }}">
    <button class="btn">Delete</button>
</form>

ASM_Duy/templates/contact/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

ASM_Duy/templates/contact/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Contact{% endblock %}

{% block body %}
    <h1>Edit Contact</h1>

    {{ include('contact/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_contact_index') }}">back to list</a>

    {{ include('contact/_delete_form.html.twig') }}
{% endblock %}

ASM_Duy/templates/contact/index.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Contact index{% endblock %}

{% block body %}
<style>
    .table {
        margin-top: 20px;
        width: 100%;
        border-collapse: collapse;
    }
    .table th,
    .table td {
        border: 1px solid #ccc;
        padding: 8px;
        text-align: left;
    }
    .table th {
        background-color: #f2f2f2;
    }
    .no-records {
        text-align: center;
        padding: 20px;
        font-style: italic;
        color: #888;
    }
</style>
<h1>Contact index</h1>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Title</th>
            <th>Note</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for contact in contacts %}
        <tr>
            <td>{{ contact.id }}</td>
            <td>{{ contact.firstName }}</td>
            <td>{{ contact.lastName }}</td>
            <td>{{ contact.email }}</td>
            <td>{{ contact.phoneNumber }}</td>
            <td>{{ contact.titleName }}</td>
            <td>{{ contact.note }}</td>
            <td>
                <a href="{{ path('app_contact_show', {'id': contact.id}) }}">show</a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="8" class="no-records">No records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

ASM_Duy/templates/contact/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Contact{% endblock %}

{% block stylesheets %}
<style>
    .login-container {
        display: grid;
       
        gap: 20px;
        height: 70vh;
    }

    .login-form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    .login-form .form-control {
        width: 300px;
        margin-bottom: 10px;
    }

    .login-title {
        text-align: center; /* Center the title text */
        margin-bottom: 20px;
    }

    .create {
        display: flex;
        justify-content: center;
        margin-top: 20px; /* Use margin-top instead of padding-top */
    }

    /* Use a more specific selector for the map container */
    .login-map-container {
        grid-column: span 1; /* Adjust the number of grid columns */
        display: flex;
        justify-content: center;
        align-items: center;
    }

    /* Responsive design for the map */
    .login-map-container iframe {
        width: 100%;
        height: 400px;
        border: 0;
    }
</style>
{% endblock %}

{% block body %}
    <div class="login-container">
        <div class="login-form">
            <h1 class="login-title">Contact</h1>
            {{ form_start(form) }}
            {{ form_row(form.first_name, { 'attr': {'class': 'form-control'} }) }}
            {{ form_row(form.last_name, { 'attr': {'class': 'form-control'} }) }}
            {{ form_row(form.email, { 'attr': {'class': 'form-control'} }) }}
            {{ form_row(form.phone_number, { 'attr': {'class': 'form-control'} }) }}
            {{ form_row(form.title_name, { 'attr': {'class': 'form-control'} }) }}
            {{ form_row(form.note, { 'attr': {'class': 'form-control', 'rows': 5} }) }}
            <div class="create">
                <button class="btn btn-primary btn-block" type="submit">Send</button>
            </div>
            {{ form_end(form) }}
        </div>
      
    </div>
{% endblock %}

ASM_Duy/templates/contact/show.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Contact{% endblock %}

{% block body %}
    <h1>Contact</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ contact.id }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ contact.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ contact.lastName }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ contact.email }}</td>
            </tr>
            <tr>
                <th>Phone_number</th>
                <td>{{ contact.phoneNumber }}</td>
            </tr>
            <tr>
                <th>Title_name</th>
                <td>{{ contact.titleName }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ contact.note }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_contact_index') }}">back to list</a>

    <a href="{{ path('app_contact_edit', {'id': contact.id}) }}">edit</a>

    {{ include('contact/_delete_form.html.twig') }}
{% endblock %}

ASM_Duy/templates/contact/success.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<style>
    .success-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .success-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    .success-message { color: green; }
</style>

<div class="success-wrapper">
    <h1>Sent Successful! ✅</h1>
    
    <p class="success-message">Thank you for yourcontact message</p>
    
    <p>This friendly message is coming from:</p>
    
    <ul>
        <a class="nav-link" href="http://127.0.0.1:8000/home">Quay về trang chủ</a>
    </ul>
</div>
{% endblock %}